ALTER DATABASE api_analytics OWNER TO jahnavi;
GRANT ALL PRIVILEGES ON DATABASE api_analytics TO jahnavi;



GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jahnavi;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jahnavi;